version: '3'

volumes:
  db:

services:
  dynamic:
    build:
      context: ../
      dockerfile: ./tasks/build.dockerfile
    ports:
      - 80:80
    environment:
      - DB_HOST=database
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    networks:
      - backend
    restart: always
    depends_on:
      - database
  database:
    image: postgres:15
    expose:
      - 5432
    volumes:
      - db:/var/lib/posgresql
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
