[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
name = "_router"
publish = false
version = "0.1.0"

[dependencies]
_database = { path = "../database", version = "*" }
_functions = { path = "../functions", version = "*" }
_utils = { path = "../utils", version = "*" }

anyhow = "^1"
base64 = "^0.21"
chrono = "^0.4"
clap = { version = "^4", features = ["derive"] }
env_logger = "^0.10"
futures = { version = "^0.3", features = ["std"], default-features = false }
hyper = { version = "^0.14", features = ["server", "http1"] }
log = "^0.4"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tokio = { version = "^1", features = ["macros"] }
tower = { version = "^0.4", features = ["make"] }
tracing = "^0.1"
tracing-subscriber = "^0.3"
url = "^2"

[dependencies.axum]
features = ["query", "headers", "multipart"]
version = "^0.6"

[dependencies.tower-http]
features = ["fs", "trace", "compression-gzip"]
version = "^0.4"

[dependencies.sea-orm]
features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "with-uuid",
  "with-chrono",
  "with-json",
]
version = "^0.11"
