[package]
authors = ["langyo <langyo.china@gmail.com>"]
edition = "2021"
publish = false
name = "_functions"
version = "0.1.0"

[dependencies]
_database = { path = "../database", version = "*" }
_utils = { path = "../utils", version = "*" }

anyhow = "^1"
chrono = "^0.4"
lazy_static = "*"
env_logger = "^0.10"
log = "^0.4"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tokio = { version = "^1", features = ["macros"] }
uuid = "^1"

moka = { version = "^0.11", features = ["future"] }

[dependencies.sea-orm]
features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "with-uuid",
  "with-chrono",
  "with-json",
]
version = "^0.11"
